GET http://localhost:3000/users

###
GET http://localhost:3000/users/21

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "diskyadit",
    "email": "diskyadit@gmail.com",
    "gender": "Male"
}